# Generated by Django 3.1.1 on 2020-09-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caffeine_mg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('impact', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
            },
        ),
        migrations.CreateModel(
            name='DrinkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_id', models.IntegerField()),
                ('entry_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'DrinkEntry',
                'verbose_name_plural': 'DrinkEntrys',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entrys',
            },
        ),
    ]
