# Generated by Django 3.0.9 on 2020-09-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caffeine_mg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('impact', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entrys',
            },
        ),
        migrations.CreateModel(
            name='DrinkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='decafrapp.Drink')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='decafrapp.Entry')),
            ],
            options={
                'verbose_name': 'DrinkEntry',
                'verbose_name_plural': 'DrinkEntrys',
            },
        ),
    ]
