# Generated by Django 3.0.9 on 2020-09-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkentry',
            old_name='drink',
            new_name='drink_id',
        ),
        migrations.RenameField(
            model_name='drinkentry',
            old_name='entry',
            new_name='entry_id',
        ),
    ]
