# Generated by Django 3.1.1 on 2020-09-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0002_auto_20200910_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkentry',
            name='drink_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='decafrapp.drink'),
        ),
        migrations.AlterField(
            model_name='drinkentry',
            name='entry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='decafrapp.entry'),
        ),
    ]
