# Generated by Django 3.0.9 on 2020-09-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0002_auto_20200915_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkentry',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='drinkentry',
            old_name='entry_id',
            new_name='entry',
        ),
    ]
