# Generated by Django 3.0.9 on 2020-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0003_auto_20200910_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='caffeine_mg',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
