# Generated by Django 3.0.9 on 2020-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0004_auto_20200916_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='impact',
            field=models.CharField(max_length=50),
        ),
    ]
