# Generated by Django 3.1.1 on 2020-09-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0005_auto_20200916_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkentry',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decafrapp.drink'),
        ),
        migrations.AlterField(
            model_name='drinkentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decafrapp.entry'),
        ),
    ]
