# Generated by Django 3.1.1 on 2020-09-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decafrapp', '0006_auto_20200921_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkentry',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='decafrapp.drink'),
        ),
        migrations.AlterField(
            model_name='drinkentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='decafrapp.entry'),
        ),
    ]
